# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trivial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trivial
  pod 'PopupDialog', '~> 1.1'
  pod 'UIGradient'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'TrivialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrivialUITests' do
    # Pods for testing
  end

end
